### ISSUE TITLE
"Extraction done !" how to remove? (Multi Extractor.exe and Tid Maker.exe)

### ISSUE THREAD

**Issue by makc-ar** [MysteryDash/MysteryDash.FileFormats#2]
Hi **MysteryDash**
Automatically how to unpack and pack all files? I use cl3_to_tid.bat and png_to.tid.bat:
for /r %%a in (*.cl3) do ".\Tools\Multi Extractor.exe" "%%a"
for /r %%a in (*.png) do ".\Tools\Tid Maker.exe" "%%a" "%%~pna.tid"

P.S. 
Pac Editor.exe and Cl3 Editor.exe command prompt versions?

**Comment by MysteryDash** [comment]
Hello,
You just need to drag&drop every file you want to extract on the multi
extractor for it to work.
As for the repacker, you just need to drag&drop the pngs onto the Tid Maker
and it'll do the same job (the file name will stay unchanged, only the
extension will be edited).

2016-11-13 19:29 GMT+01:00 makc-ar notifications@github.com:

**Comment by makc-ar** [comment]
I know, but we are doing the translation for this game and we need a console patch to make.
I removed the line Console.ReadKey(); https://github.com/MysteryDash/MysteryDash.FileFormats/blob/master/Side%20Tools/Multi%20Extractor/Program.cs and now the unpacking all files is no problem.

Need Pac Editor.exe cmd version to pach translation.
**Example**
for /r %%a in (*.pac) do ".\Tools\Pac Editor.exe" "%%a" %%~na\

**Comment by MysteryDash** [comment]
The thing is that the side tools weren't made for such uses.
They are simple examples to demonstrate how to use the library.
I can propose you two things :
- You know C# or VB.NET and basing yourself on my example you make your own
  scripts
- You don't know a .NET language and I can try to find some time to make
  you said scripts

**Comment by makc-ar** [comment]
I don't know a programming language, I'm not a hacker. Thank you for your time and attention to help me.

**Comment by MysteryDash** [comment]
No need to be a hacker to know a programming language. That's exactly why I
made this library : for people who don't have the knowledge to reverse
engineer a game.
However, if you don't know that, did you find a way to extract and repack
the texts ? Because I did not provide such a tool.

2016-11-13 22:30 GMT+01:00 makc-ar notifications@github.com:

**Comment by makc-ar** [comment]
I use text tool **neptools** https://github.com/u3shit/neptools 
Need Pac Editor.exe and Cl3 Editor.exe cmd ver. to pack.

**Comment by MysteryDash** [comment]
Neptools already contains a cl3 (un)packer and the kitserver which will
save you the time of repacking the .pac.

2016-11-13 22:43 GMT+01:00 makc-ar notifications@github.com:

**Comment by makc-ar** [comment]
kitserver is not all games working, example: Mugen Souls Z, Trillion: God of Destruction etc. Universal console packer needed 
P.S.
Trillion: God of Destruction new .tid files https://yadi.sk/d/O8r-3_llyYS8n
