### ISSUE TITLE
I got some problem in TID Maker

### ISSUE THREAD

**Issue by FrierenZk** [MysteryDash/MysteryDash.FileFormats#3]
Program.cs
line 35
`var bitmap = new Bitmap(arg);`
It throws **System.ArgumentException Parameter is not valid**.
My OS is Win10 with NET 4.6.1

**Comment by MysteryDash** [comment]
That means you didn't give a correct path to the TID Maker.
I didn't add any kind of check for the arguments you provide to the software (because this code is supposed to be an example of how to use the library) and if you drag&drop your files on the exe you shouldn't have this issue.

**Comment by FrierenZk** [comment]
But I was drap&drop my files on the exe. And I printed arg to the console before the exception occurred, it's correct value.
