### ISSUE TITLE
Black background in game after editing .TID

### ISSUE THREAD

**Issue by FantasyGensokyo** [MysteryDash/MysteryDash.FileFormats#4]
This isn't really a issue with the tools you made (which work great btw, thanks for making them!). I'm trying to change a background for one of the scenes in Megadimension Neptunia VII; but after I edit and repack the .TID, the background for that scene is black in game. Would you happen to know what's going on with that?

**Comment by MysteryDash** [comment]
Just with those informations unfortunately no, I tried myself before to
replace one of the backgrounds (first mod ever made for MegaNep btw), and
it worked.
Maybe you did something wrong ?

2017-02-05 22:22 GMT+01:00 FantasyGensokyo <notifications@github.com>:

**Comment by FantasyGensokyo** [comment]
@MysteryDash I might have. Do you remember what steps you did by any chance?

**Comment by FantasyGensokyo** [comment]
@MysteryDash Ok, so here's what I did. I tried to change the .png for GAME00000.pac/event/bg/0045.cl3/tex_00.tid/tex_00.png. I changed it to black and white and repacked/ran the game. I got a black background for the event it is used in (The event in game is called "Following Kurome"). However, that same process does work for GAME00000.pac/event/bg/0001.cl3/tex_01.tid/tex_01.png. I'm thinking the game reads certain background files differently. 

Edit: The background I edited shows up very briefly at the start of the event before it fades to black. The purple and blue window you see in the background is the fade out from the event selection menu.
![image1](https://cloud.githubusercontent.com/assets/25571333/22630834/e939553a-ebce-11e6-81bd-4228f73e45db.png)

**Comment by MysteryDash** [comment]
I think I have an idea of what's going on (something I expected to happen
while making the Tid maker but I wasn't able to find a case where this
happened).
Could you send me the two original Tid and the two Tid you made ?
Thanks.

Le 6 févr. 2017 00:00, "FantasyGensokyo" <notifications@github.com> a
écrit :

**Comment by FantasyGensokyo** [comment]
Here you go. 

[Tids.zip](https://github.com/MysteryDash/MysteryDash.FileFormats/files/756635/Tids.zip)

**Comment by MysteryDash** [comment]
I checked the Tids and they aren't at fault (both are using the same version of file of the TID structure for both the original and the modded versions).
To be honest, I don't see really why the game is doing that.
About the original background : Does it fades to black at some point in that event (if that's the case then it's a good clue, and my opinion will be that some information in the CL3 has been lost and you have to help the repacker add those missing informations) ?

**Comment by FantasyGensokyo** [comment]
The original background is fine, it's just the modded one that fades to black as soon as the event starts. Afaik the game only does that with tex_00.png files.
